//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCountry
    {
        public int Id { get; set; }
        public int CountryId { get; set; }
        public int ProductId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Product Product { get; set; }
    }
}
